#define OPCODE_INIT             0x70
#define OPCODE_RESET            0x50
#define OPCODE_READ_REG         0xB0
#define OPCODE_WRITE_REG        0x80
#define OPCODE_START_TOF        0x01

// Values shift in bits

// ****** REGISTER 0 *********************************************************

// Sets number of pulses generated by fire pulse generator. [0-15]
#define REG0_ANZ_FIRE           28

// Sets predivider for internal clock signal of fire pulse generator [0-15]
#define REG0_DIV_FIRE           24

// Sets number of periods used for calibrating the ceramic resonator [0-3]
#define REG0_ANZ_PER_CALRES     22

// Sets predivider for CLKHS [0-3]
#define REG0_DIV_CLKHS          20

// Defines the time interval the chip waits after switching on the oscillator before making a measurement [0-3]
#define REG0_START_CLKHS_1_0    18

// Enables/disables calibration calculation in the ALU
#define REG0_CALIBRATE          13

// Enables/disables auto-calibration run in the TDC, 1 = auto-calibration disabled
#define REG0_NO_CAL_AUTO        12

// 1 = measurement mode 2
#define REG0_MESSB2             11

// 0 = non-inverted input signal – rising edge
#define REG0_NEG_STOP2          10

// 0 = non-inverted input signal – rising edge
#define REG0_NEG_STOP1          9

// 0 = non-inverted input signal – rising edge
#define REG0_NEG_START          8

// ****** REGISTER 1 *********************************************************

// Defines operator for ALU data post-processing [0-15]
#define REG1_HIT2               28

// Defines operator for ALU data post-processing [0-15]
#define REG1_HIT1               24

//1 - Enables fast init operation
#define REG1_EN_FAST_INIT       23

// [0-7]
#define REG1_HITIN2             19

// [0-7]
#define REG1_HITIN1             16

// Low current option for 32 kHz oscillator.
#define REG1_CURR32K            15

// Fire pulse is used as TDC start. The START input is disabled.
#define REG1_SEL_START_FIRE     14

//Defines functionality of EN_START pin. [0-7]
#define REG1_SEL_TSTO2          11

//Defines functionality of FIRE_IN pin. [0-7]
#define REG1_SEL_TSTO1          8

// ****** REGISTER 2 *********************************************************
// Activates interrupt sources [0-7]
#define REG2_EN_INT_2_0         29

// Edge sensitivity channel 2 -> 1 = rising and falling edge
#define REG2_RFEDGE2            28

// Edge sensitivity channel 1 -> 1 = rising and falling edge
#define REG2_RFEDGE1            27

//Delay value for internal stop enable unit, hit 1 channel 1
#define REG2_DELVAL1            8

// ****** REGISTER 3 *********************************************************
// Timeout forces ALU to write ‘hFFFFFFFF
#define REG3_EN_ERR_VAL         29

// Select predivider for timeout in measurement mode 2 [0-3]
#define REG3_SEL_TIMO_MB2       27

// Delay value for internal stop enable unit, hit 2 channel 1
#define REG3_DELVAL2            8

// ****** REGISTER 4 *********************************************************
// Delay value for internal stop enable unit, hit 3 channel 1.
#define REG4_DELVAL3            8

// ****** REGISTER 5 *********************************************************
// Output configuration for pulse generator [0-7]
#define REG5_CONF_FIRE          29

// Enables additional noise for start channel
#define REG5_EN_STARTNOISE      28

// Phase noise unit - 1 = disables phase noise
#define REG5_DIS_PHASESHIFT     27

//[0-7]
#define REG5_REPEAT_FIRE        24

// Enables phase reversing for each pulse of a sequence of up to 15 possible pulses
#define REG5_PHFIRE             8

// ****** REGISTER 6 *********************************************************
// Activates the analog part
#define REG6_EN_ANALOG          31

// Sets comparator offset [0-15]
#define REG6_DA_KORR            25

// Timer to charge up the capacitor
#define REG6_TW2                22

// Specifies the default level of the inactive fire buffer. 1 = LOW
#define REG6_FIREO_DEF          14

// Option to improve the resolution
#define REG6_QUAD_RES           13

// Option to improve the resolution
#define REG6_DOUBLE_RES         12

// Highest 3 bits of the number of fire pulses.
#define REG6_ANZ_FIRE_6_4         12